import { test, expect } from '@playwright/test';
const evidence = process.env.EVIDENCE_DIR;
async function screenshot(page, name, project) { if (evidence) await page.screenshot({ path: `${evidence}/${name}-${project}.png`, fullPage: true }); }
async function noOverflow(page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); }
test('fictional exploration, filtering, question navigation and comparison', async ({ page }, info) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Big questions. Your kind of people.' })).toBeVisible();
  await screenshot(page, 'home', info.project.name);
  await noOverflow(page);
  await page.getByRole('button', { name: 'Explore the demo' }).click();
  await expect(page.getByText('8 fictional people to get to know')).toBeVisible();
  await expect(page.locator('.person-card')).toHaveCount(8);
  await page.reload();
  await expect(page.getByText('8 fictional people to get to know')).toBeVisible();
  await screenshot(page, 'discover', info.project.name);
  await noOverflow(page);
  await page.getByLabel('Search people').fill('Maya');
  await expect(page.locator('.person-card')).toHaveCount(1);
  await page.getByLabel('City or region').fill('Neverland');
  await expect(page.getByRole('heading', { name: 'No one in this little corner yet.' })).toBeVisible();
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByLabel('Age range').selectOption('40+');
  await expect(page.locator('.person-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByRole('link', { name: 'Look closer' }).first().click();
  await expect(page.locator('.match-summary')).toBeVisible();
  await expect(page.getByText('A FICTIONAL DEMO PERSON')).toBeVisible();
  await page.getByRole('button', { name: 'Differences' }).click();
  await expect(page.locator('.comparison-question').first()).toBeVisible();
  await screenshot(page, 'comparison', info.project.name);
  await noOverflow(page);
  await page.getByRole('link', { name: 'Questions', exact: true }).click();
  await expect(page.getByRole('radio').first()).toBeDisabled();
  await page.getByRole('button', { name: /Future/ }).click();
  await expect(page.getByRole('heading', { name: 'Do you want to raise children?' })).toBeVisible();
  await screenshot(page, 'questions', info.project.name);
  await noOverflow(page);
  expect(errors).toEqual([]);
});
test('real signup, save and edit, private comparisons, profile, relogin, export and deletion', async ({ page, playwright }, info) => {
  const email = `journey-${info.project.name}-${Date.now()}@example.test`;
  const peer = await playwright.request.newContext({ baseURL: 'http://127.0.0.1:8799' });
  const peerResult = await peer.post('/api/register', { data: { name: 'Avery', email: `peer-${email}`, password: 'peer-password-for-tests', age: 33, adult: true, gender: 'Nonbinary', desired: ['Nonbinary'], city: 'Testville', bio: 'A fictional test member.', interests: 'Books' } });
  expect(peerResult.status()).toBe(201);
  await peer.put('/api/answers/1', { data: { answer: 1, acceptable: [0], importance: 250, private: false, noPreference: false } });
  try {
    await page.goto('/#signup');
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('browser-password-for-tests');
    await page.getByLabel('Name', { exact: true }).fill('Taylor');
    await page.getByLabel('City or region').fill('Testville');
    await page.getByLabel('About you').fill('I love libraries and long walks.');
    await page.getByLabel('I confirm I am at least 18 years old.').check();
    await page.getByRole('button', { name: 'Create my account' }).click();
    await expect(page.getByRole('heading', { name: 'Your point of view.' })).toBeVisible();
    await page.getByRole('link', { name: 'Discover', exact: true }).click();
    await expect(page.getByText('Unknown match')).toBeVisible();
    await page.getByRole('link', { name: 'Questions', exact: true }).click();
    await page.getByRole('radio', { name: 'Gentle directness', exact: true }).focus();
    await page.keyboard.press('Space');
    await expect(page.getByRole('radio', { name: 'Gentle directness', exact: true })).toBeChecked();
    await page.getByRole('checkbox', { name: 'Gentle directness', exact: true }).check();
    await page.getByRole('radio', { name: 'Essential', exact: true }).check();
    await page.getByRole('checkbox', { name: 'Gentle directness', exact: true }).uncheck();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Answer saved. You can edit it any time.');
    await page.reload();
    await expect(page.getByRole('radio', { name: 'Gentle directness', exact: true })).toBeChecked();
    await expect(page.getByRole('checkbox', { name: 'Gentle directness', exact: true })).not.toBeChecked();
    await expect(page.getByRole('radio', { name: 'Irrelevant', exact: true })).toBeChecked();
    const partnerChoices = page.getByRole('group', { name: /Answers I’d accept from a partner/ }).locator('.answer-grid input');
    for (const choice of await partnerChoices.all()) await choice.check();
    await page.getByRole('radio', { name: 'Essential', exact: true }).check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Answer saved. You can edit it any time.');
    await page.reload();
    await expect(page.getByRole('radio', { name: 'Irrelevant', exact: true })).toBeChecked();
    for (const choice of await partnerChoices.all()) await choice.uncheck();
    await page.getByRole('checkbox', { name: 'Gentle directness', exact: true }).check();
    await page.getByRole('radio', { name: 'Essential', exact: true }).check();
    await page.getByLabel('Keep this answer private').check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Answer saved. You can edit it any time.');
    await page.reload();
    await expect(page.getByRole('radio', { name: 'Gentle directness', exact: true })).toBeChecked();
    await expect(page.getByLabel('Keep this answer private')).toBeChecked();
    await page.getByRole('link', { name: 'Discover', exact: true }).click();
    await page.getByRole('link', { name: 'Look closer' }).click();
    await expect(page.locator('.match-number strong')).toHaveText('0%');
    await expect(page.getByText(/1 shared question includes a private answer/)).toBeVisible();
    await page.getByRole('button', { name: 'Differences' }).click();
    await expect(page.locator('.comparison-question')).toHaveCount(0);
    await page.getByRole('link', { name: 'Questions', exact: true }).click();
    await page.getByLabel('Keep this answer private').uncheck();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toBeVisible();
    await page.getByRole('button', { name: 'Skip / next' }).click();
    await expect(page.getByRole('heading', { name: 'How should a couple handle a large difference in income?' })).toBeVisible();
    await page.getByRole('radio', { name: 'Proportional shared costs' }).check();
    await page.getByLabel('No preference — any answer works for me').check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toBeVisible();
    await page.getByRole('link', { name: 'Discover', exact: true }).click();
    await page.getByLabel('Search people').fill('Avery');
    await page.getByRole('link', { name: 'Look closer' }).click();
    await page.getByRole('button', { name: 'Differences' }).click();
    await expect(page.getByText('Important difference', { exact: true })).toBeVisible();
    await expect(page.getByText('Gentle directness', { exact: true })).toBeVisible();
    await page.locator('.account-nav a').click();
    await page.getByLabel('About you').fill('Updated: curious about the world.');
    await page.getByRole('button', { name: 'Save profile' }).click();
    await expect(page.getByRole('status')).toHaveText('Profile saved.');
    await page.getByRole('button', { name: 'Log out' }).click();
    await page.getByRole('link', { name: 'Log in', exact: true }).click();
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('browser-password-for-tests');
    await page.getByRole('button', { name: 'Log in', exact: true }).click();
    await expect(page.getByRole('radio', { name: 'Gentle directness', exact: true })).toBeChecked();
    await page.locator('.account-nav a').click();
    await expect(page.getByLabel('About you')).toHaveValue('Updated: curious about the world.');
    const downloadEvent = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Export my data' }).click();
    const download = await downloadEvent;
    expect(download.suggestedFilename()).toBe('okaycupid-your-data.json');
    const exported = await page.request.get('/api/export');
    expect(exported.headers()['content-disposition']).toContain('attachment');
    expect((await exported.json()).answers['2'].noPreference).toBe(true);
    await expect(page.getByRole('link', { name: 'Export my data' })).toHaveAttribute('href', '/api/export');
    await noOverflow(page);
    await page.getByLabel('Type DELETE to confirm').fill('DELETE');
    await page.getByRole('button', { name: 'Delete my account' }).click();
    await expect(page.getByRole('status')).toContainText('have been deleted');
    expect(await (await page.request.get('/api/me')).json()).toBeNull();
  } finally { await peer.delete('/api/account', { data: { confirm: 'DELETE' } }); await peer.dispose(); }
});
