import { test, expect } from '@playwright/test';
const evidence = process.env.EVIDENCE_DIR;
async function screenshot(page, name, project) { if (evidence) await page.screenshot({ path: `${evidence}/${name}-${project}.png`, fullPage: true }); }
async function noOverflow(page) { expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); }
test('fictional exploration, filtering, question navigation and comparison', async ({ page }, info) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    if (!sessionStorage.getItem('okaycupid-question-source')) sessionStorage.setItem('okaycupid-question-source', 'written');
  });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Big questions. Your kind of people.' })).toBeVisible();
  await screenshot(page, 'home', info.project.name);
  await noOverflow(page);
  await page.getByRole('button', { name: 'Explore the demo' }).click();
  await expect(page.getByText('8 fictional people to get to know')).toBeVisible();
  await expect(page.locator('.person-card')).toHaveCount(8);
  await page.reload();
  await expect(page.getByText('8 fictional people to get to know')).toBeVisible();
  await screenshot(page, 'discover', info.project.name);
  await noOverflow(page);
  await page.getByLabel('Search people').fill('Maya');
  await expect(page.locator('.person-card')).toHaveCount(1);
  await page.getByLabel('City or region').fill('Neverland');
  await expect(page.getByRole('heading', { name: 'No one in this little corner yet.' })).toBeVisible();
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByLabel('Age range').selectOption('40+');
  await expect(page.locator('.person-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByRole('link', { name: 'Look closer' }).first().click();
  await expect(page.locator('.match-summary')).toBeVisible();
  await expect(page.getByText('A FICTIONAL DEMO PERSON')).toBeVisible();
  await page.getByRole('button', { name: 'Differences' }).click();
  await expect(page.locator('.comparison-question').first()).toBeVisible();
  await screenshot(page, 'comparison', info.project.name);
  await noOverflow(page);
  await page.getByRole('link', { name: 'Questions', exact: true }).click();
  await expect(page.getByRole('radio').first()).toBeDisabled();
  await expect(page.getByLabel('Question collection')).toHaveValue('historical');
  await page.getByRole('button', { name: /Future/ }).click();
  await expect(page.getByRole('heading', { name: 'Are you looking for a partner to have children with?' })).toBeVisible();
  await screenshot(page, 'questions', info.project.name);
  await noOverflow(page);
  expect(errors).toEqual([]);
});
test('real signup, save and edit, private comparisons, profile, relogin, export and deletion', async ({ page, playwright }, info) => {
  const email = `journey-${info.project.name}-${Date.now()}@example.test`;
  const peer = await playwright.request.newContext({ baseURL: 'http://127.0.0.1:8799' });
  const peerResult = await peer.post('/api/register', { data: { name: 'Avery', email: `peer-${email}`, password: 'peer-password-for-tests', age: 33, adult: true, gender: 'Nonbinary', desired: ['Nonbinary'], city: 'Testville', bio: 'A fictional test member.', interests: 'Books' } });
  expect(peerResult.status()).toBe(201);
  const peerMember = await (await peer.get('/api/me')).json();
  await peer.put('/api/answers/167', { headers: { 'X-Expected-Member': peerMember.mutationContext }, data: { answer: 1, acceptable: [0], importance: 250, private: false, noPreference: false } });
  try {
    await page.goto('/#signup');
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('browser-password-for-tests');
    await page.getByLabel('Name', { exact: true }).fill('Taylor');
    await page.getByLabel('City or region').fill('Testville');
    await page.getByLabel('About you').fill('I love libraries and long walks.');
    await page.getByLabel('I confirm I am at least 18 years old.').check();
    await page.getByRole('button', { name: 'Create my account' }).click();
    await expect(page.getByRole('heading', { name: 'Your point of view.' })).toBeVisible();
    await page.getByRole('link', { name: 'Discover', exact: true }).click();
    await expect(page.getByText('Unknown match')).toBeVisible();
    await page.getByRole('link', { name: 'Questions', exact: true }).click();
    await expect(page.getByLabel('Question collection')).toHaveValue('historical');
    await page.getByRole('radio', { name: 'Liberal.', exact: true }).focus();
    await page.keyboard.press('Space');
    await expect(page.getByRole('radio', { name: 'Liberal.', exact: true })).toBeChecked();
    await page.getByRole('checkbox', { name: 'Liberal.', exact: true }).check();
    await page.getByRole('radio', { name: 'Essential', exact: true }).check();
    await page.getByRole('checkbox', { name: 'Liberal.', exact: true }).uncheck();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Answer saved. You can edit it any time.');
    await page.reload();
    await expect(page.getByRole('radio', { name: 'Liberal.', exact: true })).toBeChecked();
    await expect(page.getByRole('checkbox', { name: 'Liberal.', exact: true })).not.toBeChecked();
    await expect(page.getByRole('radio', { name: 'Irrelevant', exact: true })).toBeChecked();
    const partnerChoices = page.getByRole('group', { name: /Answers I’d accept from a partner/ }).locator('.answer-grid input');
    for (const choice of await partnerChoices.all()) await choice.check();
    await page.getByRole('radio', { name: 'Essential', exact: true }).check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Answer saved. You can edit it any time.');
    await page.reload();
    await expect(page.getByRole('radio', { name: 'Irrelevant', exact: true })).toBeChecked();
    for (const choice of await partnerChoices.all()) await choice.uncheck();
    await page.getByRole('checkbox', { name: 'Liberal.', exact: true }).check();
    await page.getByRole('radio', { name: 'Essential', exact: true }).check();
    await page.getByLabel('Keep this answer private').check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toHaveText('Answer saved. You can edit it any time.');
    await page.reload();
    await expect(page.getByRole('radio', { name: 'Liberal.', exact: true })).toBeChecked();
    await expect(page.getByLabel('Keep this answer private')).toBeChecked();
    await page.getByRole('link', { name: 'Discover', exact: true }).click();
    await page.getByRole('link', { name: 'Look closer' }).click();
    await expect(page.locator('.match-number strong')).toHaveText('0%');
    await expect(page.getByText(/1 shared question includes a private answer/)).toBeVisible();
    await page.getByRole('button', { name: 'Differences' }).click();
    await expect(page.locator('.comparison-question')).toHaveCount(0);
    await page.getByRole('link', { name: 'Questions', exact: true }).click();
    await expect(page.getByLabel('Question collection')).toHaveValue('historical');
    await page.getByLabel('Keep this answer private').uncheck();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toBeVisible();
    await page.getByRole('button', { name: 'Skip / next' }).click();
    await expect(page.getByRole('heading', { name: 'Which is most important to you right now?' })).toBeVisible();
    await page.getByRole('radio', { name: 'Love.' }).check();
    await page.getByLabel('No preference — any answer works for me').check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toBeVisible();
    await page.getByRole('link', { name: 'Discover', exact: true }).click();
    await page.getByLabel('Search people').fill('Avery');
    await page.getByRole('link', { name: 'Look closer' }).click();
    await page.getByRole('button', { name: 'Differences' }).click();
    await expect(page.getByText('Important difference', { exact: true })).toBeVisible();
    await expect(page.getByText('Liberal.', { exact: true })).toBeVisible();
    await page.locator('.account-nav a').click();
    await page.getByLabel('About you').fill('Updated: curious about the world.');
    await page.getByRole('button', { name: 'Save profile' }).click();
    await expect(page.getByRole('status')).toHaveText('Profile saved.');
    await page.getByRole('button', { name: 'Log out' }).click();
    await page.getByRole('link', { name: 'Log in', exact: true }).click();
    await page.getByLabel('Email', { exact: true }).fill(email);
    await page.getByLabel('Password', { exact: true }).fill('browser-password-for-tests');
    await page.getByRole('button', { name: 'Log in', exact: true }).click();
    await expect(page.getByRole('radio', { name: 'Liberal.', exact: true })).toBeChecked();
    await page.locator('.account-nav a').click();
    await expect(page.getByLabel('About you')).toHaveValue('Updated: curious about the world.');
    const downloadEvent = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Export my data' }).click();
    const download = await downloadEvent;
    expect(download.suggestedFilename()).toBe('okaycupid-your-data.json');
    const exported = await page.request.get('/api/export');
    expect(exported.headers()['content-disposition']).toContain('attachment');
    expect((await exported.json()).answers['178'].noPreference).toBe(true);
    await expect(page.getByRole('link', { name: 'Export my data' })).toHaveAttribute('href', '/api/export');
    await noOverflow(page);
    await page.getByLabel('Type DELETE to confirm').fill('DELETE');
    await page.getByRole('button', { name: 'Delete my account' }).click();
    await expect(page.getByRole('status')).toContainText('have been deleted');
    expect(await (await page.request.get('/api/me')).json()).toBeNull();
  } finally { await peer.delete('/api/account', { headers: { 'X-Expected-Member': peerMember.mutationContext }, data: { confirm: 'DELETE' } }); await peer.dispose(); }
});

test('mock Google round trip, adult onboarding, question search, save-next and durable revisit', async ({ page }, info) => {
  await page.goto('/#signup');
  await expect(page.getByRole('link', { name: 'Continue with Google' })).toBeVisible();
  await screenshot(page, 'signup-google', info.project.name);
  await page.getByRole('link', { name: 'Continue with Google' }).click();
  await expect(page.getByRole('heading', { name: 'Make it your own.' })).toBeVisible();
  expect(await (await page.request.get('/api/me')).json()).toBeNull();
  await page.getByLabel('Name', { exact: true }).fill('Mock Google adult');
  await page.getByLabel('I confirm I am at least 18 years old.').check();
  await screenshot(page, 'google-onboarding', info.project.name);
  await page.getByRole('button', { name: 'Finish joining' }).click();
  await expect(page.getByRole('heading', { name: 'Your point of view.' })).toBeVisible();
  try {
    await expect(page.getByLabel('Question collection')).toHaveValue('historical');
    await page.getByLabel('Question collection').selectOption('contemporary');
    await page.getByLabel('Search questions').fill('happy with your life');
    await expect(page.getByRole('radio', { name: 'Most of the time.', exact: true })).toBeVisible();
    await expect(page.getByText('Prompt and answer choices documented in 2011.', { exact: false })).toBeVisible();
    await page.getByRole('radio', { name: 'Most of the time.', exact: true }).check();
    await page.getByRole('checkbox', { name: 'Most of the time.', exact: true }).check();
    await page.getByRole('radio', { name: 'Very', exact: true }).check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toBeVisible();
    await page.reload();
    await expect(page.getByLabel('Question collection')).toHaveValue('contemporary');
    await page.getByLabel('Search questions').fill('happy with your life');
    await expect(page.getByRole('radio', { name: 'Most of the time.', exact: true })).toBeChecked();
    await screenshot(page, 'recovered-2011-question', info.project.name);
    await noOverflow(page);
    await page.getByLabel('Question collection').selectOption('historical');
    await page.getByLabel('Search questions').fill('dinosaurs');
    await expect(page.getByText(/Choices from a 2022 question file/)).toBeVisible();
    await expect(page.getByRole('group', { name: 'My answer', exact: true }).getByRole('radio')).toHaveCount(2);
    await screenshot(page, 'later-choices-question', info.project.name);
    await noOverflow(page);
    await page.getByLabel('Search questions').fill('around another country alone');
    await expect(page.getByRole('heading', { name: 'Have you ever traveled around another country alone?' })).toBeVisible();
    await expect(page.getByRole('link', { name: /Historical prompt/ })).toBeVisible();
    await page.getByRole('button', { name: 'Skip / next' }).click();
    await page.reload();
    await page.getByLabel('Search questions').fill('around another country alone');
    await page.getByRole('combobox', { name: 'Show', exact: true }).selectOption('skipped');
    await expect(page.getByRole('heading', { name: 'Have you ever traveled around another country alone?' })).toBeVisible();
    await page.getByRole('radio', { name: 'Yes', exact: true }).check();
    await page.getByRole('checkbox', { name: 'Yes', exact: true }).check();
    await page.getByLabel(/Why this answer/).fill('Fictional explanation: a solo train trip.');
    await page.getByLabel('Keep this answer private').check();
    await screenshot(page, 'historical-question', info.project.name);
    await noOverflow(page);
    await page.getByRole('button', { name: 'Save & next' }).click();
    await expect(page.getByRole('heading', { name: 'A fresh page.' })).toBeVisible();
    await page.getByRole('combobox', { name: 'Show', exact: true }).selectOption('answered');
    await expect(page.getByRole('radio', { name: 'Yes', exact: true })).toBeChecked();
    await expect(page.getByLabel(/Why this answer/)).toHaveValue('Fictional explanation: a solo train trip.');
    await page.getByRole('radio', { name: 'No', exact: true }).check();
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await expect(page.getByRole('status')).toBeVisible();
    await page.getByRole('button', { name: 'Log out' }).click();
    await page.getByRole('link', { name: 'Log in', exact: true }).click();
    await page.getByRole('link', { name: 'Continue with Google' }).click();
    await expect(page.getByRole('heading', { name: 'Your point of view.' })).toBeVisible();
    await page.getByLabel('Search questions').fill('around another country alone');
    await expect(page.getByRole('radio', { name: 'No', exact: true })).toBeChecked();
    await expect(page.getByLabel('Keep this answer private')).toBeChecked();
    await noOverflow(page);
  } finally { await page.request.delete('/api/account', { headers: { 'X-Expected-Member': (await (await page.request.get('/api/me')).json())?.mutationContext }, data: { confirm: 'DELETE' } }).catch(() => {}); }
});

test('drafts survive navigation and stale tabs cannot save into another account', async ({ page }, info) => {
  const profile = name => ({ name, email: `${name}-${info.project.name}-${Date.now()}@example.test`, password: 'fictional-draft-password', age: 30, adult: true, gender: 'Nonbinary', desired: ['Nonbinary'], city: '', bio: '', interests: '' });
  const ownerProfile = profile('DraftOwner');
  await page.request.post('/api/register', { data: ownerProfile });
  await page.goto('/#questions');
  await page.getByRole('radio', { name: 'Liberal.', exact: true }).check();
  await page.getByLabel(/Why this answer/).fill('Fictional private draft stays with its author');
  await page.getByLabel('Keep this answer private').check();
  await page.getByRole('link', { name: 'How it works', exact: true }).click();
  await page.getByRole('link', { name: 'Questions', exact: true }).click();
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('Fictional private draft stays with its author');
  await expect(page.getByRole('radio', { name: 'Liberal.', exact: true })).toBeChecked();
  await page.getByLabel('Search questions').fill('dinosaurs');
  await page.getByLabel('Search questions').fill('');
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('Fictional private draft stays with its author');
  await page.getByRole('link', { name: 'okaycupid home', exact: true }).click();
  await page.getByRole('button', { name: 'Explore the demo' }).click();
  await page.getByRole('link', { name: 'Questions', exact: true }).click();
  await expect(page.getByLabel(/Why this answer/)).not.toHaveValue('Fictional private draft stays with its author');
  await expect(page.getByLabel(/Why this answer/)).toBeDisabled();
  await page.getByRole('button', { name: /Return to real members/ }).click();
  await page.getByRole('link', { name: 'Questions', exact: true }).click();
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('Fictional private draft stays with its author');
  await expect(page.getByLabel('Keep this answer private')).toBeChecked();
  await page.locator('.account-nav a').click();
  await page.getByLabel('About you').fill('Fictional unsaved biography');
  await page.getByRole('link', { name: 'How it works', exact: true }).click();
  await page.locator('.account-nav a').click();
  await expect(page.getByLabel('About you')).toHaveValue('Fictional unsaved biography');
  await screenshot(page, 'preserved-profile', info.project.name);
  await page.getByRole('link', { name: 'Questions', exact: true }).click();
  const warning = page.waitForEvent('dialog');
  await page.evaluate(() => { setTimeout(() => location.reload(), 0); });
  const dialog = await warning;
  expect(dialog.type()).toBe('beforeunload');
  await dialog.dismiss();
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('Fictional private draft stays with its author');
  await screenshot(page, 'preserved-draft', info.project.name);
  const owner = await (await page.request.get('/api/me')).json();
  let releaseOldResponse;
  let markCaptured;
  const captured = new Promise(resolve => { markCaptured = resolve; });
  let hold = true;
  await page.route('**/api/me', async route => {
    if (!hold) return route.continue();
    hold = false;
    const response = await route.fetch();
    markCaptured();
    await new Promise(resolve => { releaseOldResponse = resolve; });
    await route.fulfill({ response });
  });
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await captured;
  const otherTab = await page.context().newPage();
  await otherTab.request.post('/api/logout', { headers: { 'X-Expected-Member': owner.mutationContext }, data: {} });
  await otherTab.request.post('/api/register', { data: profile('OtherMember') });
  const rejected = page.waitForResponse(response => response.url().endsWith('/api/answers/167') && response.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Save answer', exact: true }).click();
  expect((await rejected).status()).toBe(409);
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('');
  const current = await (await page.request.get('/api/me')).json();
  expect(current.name).toBe('OtherMember');
  expect(current.answers).toEqual({});
  releaseOldResponse();
  await expect(page.locator('.account-nav a')).toContainText('OtherMember');
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('');
  await screenshot(page, 'stale-draft-rejected', info.project.name);
  await page.locator('.account-nav a').click();
  await expect(page.getByLabel('About you')).toHaveValue('');
  const storage = await page.evaluate(() => JSON.stringify([Object.entries(localStorage), Object.entries(sessionStorage)]));
  expect(storage).not.toContain('Fictional private draft');
  await page.request.delete('/api/account', { headers: { 'X-Expected-Member': current.mutationContext }, data: { confirm: 'DELETE' } });
  await page.request.post('/api/login', { data: { email: ownerProfile.email, password: ownerProfile.password } });
  const returnedOwner = await (await page.request.get('/api/me')).json();
  expect((await page.request.delete('/api/account', { headers: { 'X-Expected-Member': returnedOwner.mutationContext }, data: { confirm: 'DELETE' } })).status()).toBe(200);
});

test('reload warning clears after saving normalized answers or removing them', async ({ page }, info) => {
  await page.request.post('/api/register', { data: { name: 'Warning test', email: `warning-${info.project.name}@example.test`, password: 'fictional-warning-password', age: 30, adult: true, gender: 'Nonbinary', desired: ['Nonbinary'], city: '', bio: '', interests: '' } });
  await page.goto('/#questions');
  await page.getByRole('radio', { name: 'Liberal.', exact: true }).check();
  await page.getByLabel(/Why this answer/).fill('  Fictional normalized explanation  ');
  await page.getByLabel(/No preference/).check();
  await page.getByRole('button', { name: 'Save answer', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Answer saved');
  expect(await page.evaluate(() => !window.dispatchEvent(new Event('beforeunload', { cancelable: true })))).toBe(false);
  await page.reload();
  await expect(page.getByLabel(/Why this answer/)).toHaveValue('Fictional normalized explanation');
  await page.getByRole('button', { name: 'Remove saved answer' }).click();
  await expect(page.getByRole('status')).toContainText('removed');
  expect(await page.evaluate(() => !window.dispatchEvent(new Event('beforeunload', { cancelable: true })))).toBe(false);
  const member = await (await page.request.get('/api/me')).json();
  await page.request.delete('/api/account', { headers: { 'X-Expected-Member': member.mutationContext }, data: { confirm: 'DELETE' } });
});
