const groups = [
['Values', [
['When honesty might hurt someone, what do you usually choose?', 'Gentle directness|Wait for a better moment|Only speak if asked|Say it plainly right away'],
['How should a couple handle a large difference in income?', 'Proportional shared costs|Equal shared costs|Mostly separate spending|Decide case by case'],
['What makes a promise worth keeping?', 'The commitment itself|Its effect on others|Whether it still makes sense|All of these'],
['What is your relationship with ambition?', 'A central driving force|One part of a balanced life|Mostly about helping others|I prefer contentment'],
['How much does ethical sourcing affect your purchases?', 'Nearly always|When affordable|Occasionally|Rarely'],
['When a rule seems unfair, what feels right?', 'Challenge it openly|Work to change it gradually|Make a personal exception|Follow it anyway'],
['How do you feel about inherited wealth?', 'A responsibility to redistribute|A family resource to steward|A private matter|Still thinking about it'],
['What does generosity most often look like for you?', 'Giving time|Giving money|Sharing practical skills|Making space for people'],
['How important is voting to you?', 'An essential responsibility|Important when possible|One of many civic tools|Not important to me'],
['Should a partner share your political outlook?', 'Closely|On core rights only|Difference is welcome|It does not matter'],
['How do you respond when your group excludes someone?', 'Speak up immediately|Talk privately afterward|Invite the person myself|First understand why'],
['What matters most when choosing work?', 'Social usefulness|Financial stability|Creative freedom|Time outside work'],
['How much personal convenience would you give up for the environment?', 'A great deal|Some regularly|A little|Very little'],
['What do you admire most in a person?', 'Integrity|Curiosity|Kindness|Courage'],
['How do you think about forgiveness?', 'Possible with changed behavior|Usually worth offering|A personal choice, never owed|Hard for me'],
['Is it important to admit being wrong in public?', 'Yes, openly|Usually, briefly|A private correction is enough|It depends on the stakes'],
['What does financial success mean to you?', 'Security and enough|Freedom to explore|Ability to support others|Building substantial wealth'],
['How much should family tradition guide adult choices?', 'A lot|Some|Only when freely chosen|Very little'],
['How do you view peaceful protest?', 'I actively participate|I support it|It depends on the cause|I generally avoid it'],
['When loyalty and fairness conflict, which guides you?', 'Fairness first|Loyalty first|Seek a compromise|The specifics decide']]],
['Relationships', [
['What kind of relationship are you looking for?', 'Monogamous partnership|Consensual nonmonogamy|Open to either|Still exploring'],
['How much independent time feels healthy in a partnership?', 'A little each day|Several evenings a week|Lots of separate time|Mostly together time'],
['How soon do you prefer to discuss relationship intentions?', 'Before meeting|On an early date|After a few dates|Let it develop naturally'],
['How do you prefer to show affection?', 'Words|Touch with consent|Helpful actions|Shared experiences'],
['What pace of commitment suits you?', 'Slow and deliberate|A few months of discovery|Fast when it feels right|No fixed timeline'],
['How do you feel about staying friends with former partners?', 'Usually positive|Fine with clear boundaries|Often uncomfortable|Depends on the history'],
['How important is marriage to your future?', 'Essential|Nice but optional|Not for me|Undecided'],
['How would you handle attraction to someone outside your relationship?', 'Discuss agreed boundaries|Reflect privately first|Create distance|Depends on our agreements'],
['What does a satisfying date look like?', 'A long conversation|Doing something new|A quiet familiar ritual|A playful adventure'],
['How much should partners know about each other’s past?', 'Whatever each chooses to share|Most meaningful experiences|Only what affects the present|I value very open histories'],
['Would you consider a long-distance relationship?', 'Yes, indefinitely|With a plan to reunite|Only briefly|No'],
['How do you feel about public affection?', 'Very comfortable|Small gestures are lovely|Prefer privacy|Depends on the setting'],
['What role should separate friendships play?', 'A major independent part of life|A balance with shared friends|Mostly shared circles|Whatever works for each person'],
['How should partners approach phone privacy?', 'No expectation of access|Shared access by invitation|Mutual open access|Discuss as trust develops'],
['When do you feel most cared for?', 'When someone listens|When someone follows through|When someone makes time|When someone notices details'],
['How often do you like checking in when apart?', 'Several times a day|Once a day|Every few days|No regular expectation'],
['What is your view of couples counseling?', 'Useful even before problems|Useful during difficulties|A last resort|Not something I want'],
['How do you prefer to celebrate anniversaries?', 'A meaningful small ritual|A big occasion|Spontaneously|No celebration needed'],
['How much overlap in hobbies do you want?', 'A lot|A few shared interests|Very little is fine|No preference'],
['What makes a relationship feel secure?', 'Consistent actions|Explicit reassurance|Shared plans|Room to be independent']]],
['Lifestyle', [
['What rhythm suits your mornings?', 'Early and energetic|Slow and quiet|Different every day|Mornings are a struggle'],
['How tidy do you like your living space?', 'Very orderly|Comfortably lived in|Creative clutter|Not a priority'],
['How do you approach alcohol?', 'I do not drink|Occasional drink|Regular social drinking|It is part of many evenings'],
['How do you feel about smoking in your home?', 'Never indoors|Only outside|Occasionally indoors is fine|Comfortable with it'],
['What is your preferred approach to meals?', 'Cook most days|Mix cooking and eating out|Simple minimal preparation|Explore restaurants often'],
['What kind of neighborhood feels like home?', 'Busy urban center|Walkable smaller town|Quiet suburb|Rural space'],
['How important is exercise in your week?', 'A daily anchor|A few times a week|Occasional activity|Not a priority'],
['What is your relationship with pets?', 'I have or want pets|Happy living with a partner’s pets|Prefer a pet-free home|Depends on the animal'],
['How do you spend an unexpected free evening?', 'See people|Make something|Rest at home|Go exploring'],
['How do you manage your budget?', 'Detailed planning|Loose guidelines|Save first, spend the rest|Mostly spontaneous'],
['What temperature feels best at home?', 'Cool and layered|Moderate|Warm and cozy|Flexible'],
['How much advance planning do you like for weekends?', 'Plan everything|One or two anchors|Mostly spontaneous|Entirely open'],
['How do you feel about hosting overnight guests?', 'Love it often|Occasionally welcome|Only close people|Prefer not to'],
['What is your usual sleep schedule?', 'Early nights|Late nights|Fairly flexible|Variable due to work or care'],
['How would you approach shared chores?', 'A regular rota|Divide by preference|Notice and do what is needed|Arrange outside help if possible'],
['How much screen-free time do you want together?', 'Most shared time|A daily stretch|Occasional breaks|Little restriction'],
['What is your approach to possessions?', 'Keep very little|Keep useful and meaningful things|I enjoy collections|I like plenty of choice'],
['How do you feel about recreational cannabis where legal?', 'Not for me or my home|Fine if others use it|Occasional use|Regular use'],
['How do you prefer to travel locally?', 'Walk or cycle|Public transport|Drive|Whatever is practical'],
['What role does quiet play in your home?', 'Quiet is essential|A balance is best|Background sound is welcome|I enjoy a lively home']]],
['Philosophy', [
['What best describes your spiritual life?', 'Religious practice|Spiritual without religion|Secular|Questioning'],
['How comfortable are you with unanswered big questions?', 'Very comfortable|Mostly comfortable|I keep seeking answers|Uncertainty is difficult'],
['What gives life a sense of meaning for you?', 'Relationships|Service|Discovery|Creating things'],
['Do you think people can change deeply?', 'Yes, with effort|Sometimes|Rarely|I am unsure'],
['How do you approach an unfamiliar belief?', 'Ask curious questions|Read about it privately|Compare it with evidence|Wait until it affects me'],
['What role should religion play in a shared home?', 'A central shared practice|Room for individual practices|Cultural traditions only|Little or none'],
['How do you make a difficult moral decision?', 'Principles|Likely consequences|Care for those involved|A mix of approaches'],
['How do you feel about changing your mind?', 'It is a strength|Welcome with strong evidence|It can be unsettling|I prefer settled convictions'],
['What do you think about luck and achievement?', 'Luck plays a large role|Effort and luck both matter|Effort matters most|Hard to separate them'],
['How often do you reflect on mortality?', 'Often and openly|Occasionally|Rarely|I prefer not to'],
['What is your attitude toward scientific uncertainty?', 'A normal part of learning|Frustrating but necessary|Reason for caution|I prefer clear conclusions'],
['What kind of future do you expect for the world?', 'Mostly hopeful|Mixed|Mostly worried|Too uncertain to say'],
['What role does beauty play in your daily life?', 'Essential nourishment|A welcome pleasure|Something I notice occasionally|Not a major focus'],
['How do you understand personal freedom?', 'Room to choose my path|Freedom with mutual responsibilities|Independence from institutions|Freedom from material insecurity'],
['How do you feel about rituals?', 'I love inherited rituals|I enjoy making new ones|Occasionally meaningful|They do little for me'],
['What is your attitude toward competition?', 'Energizing|Fun in small doses|Useful with limits|I prefer cooperation'],
['How do you approach advice?', 'Seek it widely|Ask a trusted few|Reflect alone first|Learn by trying'],
['What does a good life need most?', 'Connection|Purpose|Peace|Adventure'],
['How comfortable are you discussing different worldviews?', 'Very, even passionately|With mutual care|Only occasionally|I prefer shared views'],
['What is your relationship with nostalgia?', 'A source of comfort|Enjoy it without dwelling|Mostly look forward|Mixed feelings']]],
['Community', [
['How connected do you want to be to your neighbors?', 'Know and help many|Friendly with a few|Polite familiarity|Mostly private'],
['How often do you volunteer?', 'Regularly|Occasionally|I would like to start|Not currently interested'],
['What size social gathering suits you?', 'One or two people|A small group|A lively crowd|Depends on my energy'],
['How involved is your family in daily life?', 'Very involved|Regular contact|Occasional contact|Little or no contact'],
['How should a couple handle different holiday traditions?', 'Alternate|Combine them|Create new ones|Celebrate separately sometimes'],
['What role do chosen families play for you?', 'Central|Important alongside relatives|Still building one|Not a familiar part of my life'],
['How do you support a friend in a hard season?', 'Listen regularly|Offer practical help|Invite them into ordinary life|Ask exactly what they need'],
['How much social time feels right in a week?', 'Most days|A few times|Once or twice|Less than weekly'],
['How do you prefer to meet new people?', 'Through friends|Shared activities|Community events|One-to-one introductions'],
['What would you do with a shared neighborhood space?', 'Plant a garden|Host meals|Create a workshop|Keep a quiet retreat'],
['How do you feel about organizing gatherings?', 'I love taking the lead|Happy to share the work|Prefer attending|Prefer small spontaneous plans'],
['How important is accessibility when making group plans?', 'A first consideration|Important when needs are known|I am learning about it|Not something I often consider'],
['What do you value most in friendship?', 'Reliability|Honesty|Shared joy|Mutual growth'],
['How do you approach lending money to friends?', 'Within a clear limit|Only as a gift|Case by case|I avoid it'],
['How much do you enjoy intergenerational friendships?', 'A lot|Some|Most friends are my age|I have not considered it'],
['What is your response to local issues?', 'Get actively involved|Stay informed|Help when asked|Focus on personal life'],
['How would you welcome a new person into a group?', 'Introduce them around|Have a quiet conversation|Invite them to an activity|Give them room to settle'],
['How important is living near loved ones?', 'Essential|A strong preference|Nice but flexible|Not important'],
['How do you feel about sharing tools and resources?', 'Enthusiastic|Happy with clear agreements|With close friends only|Prefer separate ownership'],
['What kind of community commitment appeals to you?', 'Long-term local service|Occasional projects|Informal mutual help|I prefer flexibility']]],
['Communication', [
['When upset, what helps you communicate?', 'Talk soon|Take a short break first|Write down my thoughts|Sleep on it'],
['How do you prefer to receive difficult feedback?', 'Directly and kindly|With examples and time|In writing|After being asked if I am ready'],
['What does a useful apology include?', 'Taking responsibility|A concrete repair|Understanding the impact|All of these'],
['How do you handle interruptions in conversation?', 'Address them directly|Return to my point later|Usually let them go|Depends on context'],
['How comfortable are you naming your needs?', 'Very comfortable|Getting better at it|I need encouragement|It is difficult'],
['What is your style in a disagreement?', 'Explore every angle|Find practical next steps|Focus on feelings|Pause until calmer'],
['How do you feel about playful teasing?', 'Love it with trust|Gentle teasing is fine|Only on certain topics|Prefer none'],
['How should partners signal a need for space?', 'Say it directly with a return time|Use an agreed phrase|Send a message|Whatever feels natural'],
['How do you approach a misunderstood text?', 'Ask what they meant|Call or meet|Explain my interpretation|Wait before responding'],
['How much emotional detail do you like to share?', 'A great deal|A moderate amount|Only key feelings|I am quite private'],
['What makes you feel heard?', 'Thoughtful questions|Reflecting back my meaning|Undivided attention|A helpful response'],
['How do you feel about debating for fun?', 'Love it|Sometimes enjoy it|Only on low-stakes topics|Not enjoyable'],
['When plans change, what communication do you expect?', 'As much notice as possible|A quick message|An explanation when we meet|I am flexible'],
['How do you prefer to resolve recurring friction?', 'Scheduled check-in|Talk when it arises|Try a practical experiment|Seek outside guidance'],
['How comfortable are you saying no?', 'Very|Usually|With reassurance|I find it hard'],
['How do you respond when someone cries?', 'Ask what would help|Offer quiet company|Offer comfort with consent|Give them space'],
['How do you like to discuss money?', 'Regularly and openly|When decisions arise|With clear numbers first|Slowly, it feels personal'],
['How important is humor during hard conversations?', 'Often helpful|Sometimes helpful|Only afterward|I prefer seriousness'],
['What is your preferred way to reconnect after conflict?', 'Talk through the repair|Spend gentle time together|A caring gesture|Some space then a fresh start'],
['How do you handle not knowing what you feel?', 'Talk it out|Journal or reflect|Move or make something|Give it time']]],
['Interests', [
['What kind of book are you most likely to pick up?', 'Fiction|History or biography|Science or ideas|Poetry or essays'],
['What sounds like a satisfying Saturday outing?', 'Museum or gallery|Hike or park|Market or food tour|Live music or theater'],
['How do you engage with music?', 'Listen closely|Play or sing|Dance|Enjoy it in the background'],
['What kind of creative activity appeals to you?', 'Writing or drawing|Making useful objects|Cooking or gardening|Performing or improvising'],
['How do you feel about board games?', 'Love strategic games|Prefer light party games|Occasionally fun|Not my thing'],
['What is your approach to learning a new skill?', 'Take a class|Experiment alone|Learn with friends|Follow a guide'],
['What travel experience appeals most?', 'Deep time in one place|A many-stop adventure|Nature and quiet|Visiting people I care about'],
['How much do you enjoy watching sports?', 'A lot|Sometimes|For the social occasion|Very little'],
['What kind of films draw you in?', 'Character-driven stories|Documentaries|Comedy|Fantasy or adventure'],
['How do you feel about dancing?', 'Any chance I get|With people I trust|I would like to learn|I prefer watching'],
['What is your ideal outdoor activity?', 'Gentle walk|Challenging hike|Water activity|Sitting somewhere beautiful'],
['How adventurous are you with food?', 'Try almost anything|Curious within limits|Prefer familiar favorites|Limited by needs or preference'],
['What do you enjoy collecting?', 'Stories and experiences|Books or records|Objects with history|Nothing in particular'],
['How do you feel about home projects?', 'Love a big project|Enjoy small improvements|Only when necessary|Prefer getting help'],
['What role do video games play in your life?', 'A regular hobby|Occasional fun|Mostly social play|Little or none'],
['How do you like to explore a new city?', 'Wander on foot|Follow a researched plan|Ask local people|Visit a few highlights'],
['What kind of class would you choose together?', 'Pottery or art|Cooking|Dance or movement|Language or history'],
['How much do you enjoy camping?', 'Love it|With some comforts|For a special occasion|Prefer a bed indoors'],
['What draws you to a hobby?', 'Mastering a skill|Relaxing|Finding community|Expressing myself'],
['How do you feel about trying a partner’s favorite activity?', 'Eager to try|Happy occasionally|If they also try mine|Prefer independent hobbies']]],
['Future', [
['Do you want to raise children?', 'Yes|No|Maybe|Already parenting, open to discussion'],
['How do you feel about moving for a partner?', 'Open to it|Only with shared benefits|Within my region|I need to stay rooted'],
['What kind of home do you imagine long term?', 'Small and simple|Room for family and guests|Shared community living|Still exploring'],
['How far ahead do you like to plan?', 'Years|About a year|A few months|Mostly the present'],
['How would you approach caring for aging relatives?', 'Bring care close to home|Share care with others|Arrange professional support|Depends on resources and needs'],
['What is your attitude toward career changes?', 'Exciting possibilities|Worth careful planning|Prefer stability|Already making a change'],
['How important is owning a home?', 'A major goal|Nice if possible|Renting suits me|Not important'],
['What would you prioritize with more free time?', 'Loved ones|Creative work|Community contribution|Travel and exploration'],
['How do you approach retirement planning?', 'Save consistently now|Balance saving and living|Expect a flexible working life|Still figuring it out'],
['What role might education play in your future?', 'Formal study|Lifelong informal learning|Learning for a career shift|No major plans'],
['How would you divide parenting responsibilities if relevant?', 'As equally as possible|By strengths and schedules|One primary caregiver by agreement|I do not plan to parent'],
['What pace of life do you hope for in ten years?', 'Slower|Similar to now|More adventurous|Hard to predict'],
['How would you handle a major shared financial setback?', 'Make a plan together|Reduce costs immediately|Seek trusted advice|Focus on reassurance first'],
['Would you consider living abroad?', 'Definitely|For a limited time|Only for a strong reason|No'],
['What kind of legacy matters to you?', 'People feeling loved|Useful work|Positive community change|A life honestly lived'],
['How do you feel about combining finances?', 'Mostly combined|Shared fund plus separate money|Mostly separate|Decide when the time comes'],
['What place does adventure have in your long-term plans?', 'A central place|Regular small adventures|Occasional exceptions|Stability matters more'],
['How would you approach a partner’s demanding care needs?', 'Learn and adapt together|Build a wider support network|Discuss sustainable limits|It depends on the situation'],
['What would make you feel ready for a big life change?', 'A detailed plan|A financial cushion|Support from loved ones|A strong sense of purpose'],
['What do you hope a future partner helps you do?', 'Grow|Feel at home|Explore|Build something meaningful']]]
];
export const questions = groups.flatMap(([topic, entries], t) => entries.map(([prompt, choices], i) => ({ id: t * 20 + i + 1, topic, prompt, options: choices.split('|') })));
export const topics = groups.map(([name]) => name);
